version: '3.8'

services:
  db:
    env_file: 
      - path: ./envvars/db.env
    image: postgres:latest
    container_name: my_postgres
    ports:
      - 5433:5432
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - main
    
  urfuture:
    container_name: "urfuture"
    env_file: 
      - path: ./envvars/db.env
    image: urfuture:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - main

  nginx:
    container_name: "nginx"
    image: nginx:alpine
    volumes:
      - ./envvars/nginx/certs:/etc/nginx/ssl
      - ./envvars/nginx/urfuture.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - urfuture
    networks:
      - main


networks:
  main:
    driver: bridge